# Generated by Django 2.2.10 on 2020-03-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20200226_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='')),
                ('last_name', models.CharField(max_length=64, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('address', models.CharField(max_length=256, verbose_name='')),
                ('postal_code', models.CharField(max_length=20, verbose_name='')),
                ('city', models.CharField(max_length=100, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='')),
                ('paid', models.BooleanField(default=False, verbose_name='')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.Order', verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='main.Product', verbose_name='')),
            ],
        ),
    ]
